spring.datasource.url=jdbc:mysql://localhost:3306/jobflow?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=jobflow
spring.datasource.password=jobflow
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.flyway.enabled=false

spring.jpa.hibernate.ddl-auto=validate
