import React from 'react';
import { CheckCircle2 } from 'lucide-react';
import { Badge, Button, ProgressBar } from '../components/ui.jsx';

export function DemoStatusPage({ go }) {
  const health = [['backend-api', '8080', '99.98%'], ['mysql-primary', '3306', '99.99%'], ['redis-cache', '6379', '100%'], ['elasticsearch', '9200', '99.95%'], ['prometheus', '9090', '99.97%'], ['grafana', '3000', '99.96%'], ['zipkin', '9411', '99.95%']];
  const smokes = ['search.precision@5', 'redis.cache.smoke', 'jd.match.smoke', 'gap.analysis.v2', 'recommendation.api', 'deadline.reminder', 'daily.digest.smoke', 'grafana.scrape'];
  return <main className="page"><div className="page-head"><div><h1>Demo Status</h1><p>포트폴리오 시연용 운영 콘솔입니다. 일반 사용자 네비게이션에는 노출하지 않습니다.</p></div><div style={{ display: 'flex', gap: 8 }}><Button variant="light" onClick={() => go('home')}>사용자 홈</Button><Button variant="lime" onClick={() => go('project-analysis', 1)}>핵심 플로우 보기</Button></div></div><section className="demo-console"><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 18, flexWrap: 'wrap', gap: 12 }}><Badge tone="lime">ALL SYSTEMS OPERATIONAL</Badge><span style={{ color: '#aeb7c6' }}>env=local-preview · build=demo · uptime 99.97%</span></div><div className="grid grid-4">{[['REAL JOBS INDEXED', '314', 'JUMPIT · WANTED 수집'], ['SEARCH PRECISION@5', '0.900', 'real-source eval'], ['REQ THROUGHPUT', '1.2k', 'k6 scenario'], ['BATCH PROCESSED', '10k', 'mock retry verified']].map(([l, v, s]) => <div className="console-card" key={l}><h3>{l}</h3><div className="console-value">{v}</div><p style={{ color: '#7f8999' }}>{s}</p><ProgressBar value={70 + v.length * 3} /></div>)}</div><div className="console-grid" style={{ marginTop: 14 }}><div className="console-card"><h3>SYSTEM HEALTH</h3>{health.map(([n, port, up]) => <div className="console-row" key={n}><span><CheckCircle2 size={14} color="var(--lime)" /> {n}<small style={{ color: '#697080' }}>:{port}</small></span><span>ok</span><b style={{ color: 'var(--lime)' }}>{up}</b></div>)}</div><div className="console-card"><h3>DATA PIPELINE</h3>{['GitHub analysis → skill inventory', 'collector → normalize → ES index', 'JD match → gap → recommendation', 'outbox → batch → retry / idempotency'].map((x, i) => <div className="console-row" key={x}><Badge tone="lime">{['ingest', 'index', 'serve', 'notify'][i]}</Badge><span>{x}</span><b style={{ color: 'var(--lime)' }}>✓</b></div>)}</div></div><div className="console-grid" style={{ marginTop: 14 }}><div className="console-card"><h3>CI · SMOKE RESULTS</h3>{smokes.map((s, i) => <div className="console-row" key={s}><span>✓ {s}</span><span>{['0.9000', 'hit/miss ok', 'top 79.95', 'evidence 8+', 'excluded ok', '10k / retry', 'retry ok', 'target up'][i]}</span><b>{[212, 9, 146, 188, 94, 1200, 420, 15][i]}ms</b></div>)}</div><div className="grid"><div className="console-card"><h3>SKILL MAPPING MISS</h3><div className="console-value" style={{ color: 'var(--lime)' }}>0.0%</div><p style={{ color: '#7f8999' }}>alias backfill 후 미매핑 0건</p></div><div className="console-card"><h3>INDEXED SKILLS</h3><div className="console-value">1,367</div><p style={{ color: '#7f8999' }}>job_skill_index rows</p></div><div className="console-card" style={{ borderColor: 'rgba(185,236,42,.4)' }}><h3>OBSERVABILITY</h3><div className="console-value">UP</div><p style={{ color: '#7f8999' }}>Prometheus + Grafana 연동</p></div></div></div></section></main>;
}

export function ErrorPage({ code, go }) {
  const map = { '401': ['로그인이 필요합니다', '보호된 화면입니다. 로그인 후 다시 시도해주세요.', 'login'], '403': ['접근 권한이 없습니다', 'GitHub 권한 또는 계정 권한을 확인해야 합니다.', 'mypage'], '404': ['페이지를 찾을 수 없습니다', '주소가 바뀌었거나 아직 구현되지 않은 화면입니다.', 'home'], '500': ['서버 오류가 발생했습니다', '잠시 후 다시 시도하거나 Demo Status에서 상태를 확인하세요.', 'demo-status'], oauth: ['OAuth 로그인이 완료되지 않았습니다', '승인이 취소되었거나 authorization code가 만료되었습니다.', 'login'] };
  const [title, desc, action] = map[code] || map['404'];
  return <main className="auth-page"><section className="tile" style={{ padding: 36, width: 'min(560px, 100%)' }}><p className="eyebrow">{code}</p><h1>{title}</h1><p style={{ color: 'var(--muted)', lineHeight: 1.6 }}>{desc}</p><Button variant="dark" onClick={() => go(action)}>이동하기</Button></section></main>;
}

export function OnboardingPage({ go }) {
  return <main className="page"><div className="page-head"><div><h1>온보딩</h1><p>직무, 연차, 보유 스킬을 먼저 입력하고 레포지토리 연결로 정확도를 올립니다.</p></div></div><section className="tile" style={{ padding: 28 }}><div className="grid grid-3">{['직무 선택', '스킬 입력', '레포지토리 연결'].map((x, i) => <div className="tile" style={{ padding: 20 }} key={x}><Badge tone="lime">STEP {i + 1}</Badge><h2>{x}</h2><p style={{ color: 'var(--muted)' }}>{i === 2 ? 'GitHub 레포를 연결하면 코드 근거 기반 매칭으로 전환됩니다.' : '초기 추천을 만들기 위한 최소 정보입니다.'}</p></div>)}</div><Button variant="lime" style={{ marginTop: 20 }} onClick={() => go('projects')}>레포지토리 연결</Button></section></main>;
}
